FROM golang:alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o mock-api ./cmd/mock/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/mock-api .
EXPOSE 8081
CMD ["./mock-api"]