name: E2E and Unit Tests

on:
  push:
    branches: [ "main", "master", "feature/*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Поднимаем Docker Compose и запускаем тесты
      - name: Run E2E and Unit Tests
        run: |
          docker compose --env-file .env.e2e -f compose.e2e.yaml up --build --exit-code-from tests

      # 3. Чистим за собой контейнеры
      - name: Down docker compose
        if: always()
        run: |
          docker compose -f compose.e2e.yaml down -v